// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMVCCore7_1.Models;

#nullable disable

namespace WebMVCCore7_1.Migrations
{
    [DbContext(typeof(BusinessDbContext))]
    partial class BusinessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMVCCore7_1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebMVCCore7_1.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebMVCCore7_1.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Recrutement")
                        .HasColumnType("date");

                    b.Property<decimal?>("Salaire")
                        .HasColumnType("money");

                    b.HasKey("Id")
                        .HasName("PK__Employee__3214EC079FA03943");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WebMVCCore7_1.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Prix")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("WebMVCCore7_1.Models.Produit", b =>
                {
                    b.HasOne("WebMVCCore7_1.Models.Category", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .HasConstraintName("FK_Produits_Categories");

                    b.HasOne("WebMVCCore7_1.Models.Client", "Client")
                        .WithMany("Produits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Produits_Clients");

                    b.HasOne("WebMVCCore7_1.Models.Employee", "Employee")
                        .WithMany("Produits")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Produits_Employees");

                    b.Navigation("Categorie");

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WebMVCCore7_1.Models.Category", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("WebMVCCore7_1.Models.Client", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("WebMVCCore7_1.Models.Employee", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
