//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Produits = new HashSet<Produit>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
    
        //Propriété de naviguation
        public virtual ICollection<Produit> Produits { get; set; }
    }
}
